load("@rules_java//java:java_binary.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
	name = "thread",
	srcs = [glob("*.java")],
	deps = "/../standard:standard"
)