load("@rules_java//java:java_library.bzl", "java_library")

package(default_visibility = ["//visibility:public"])

java_library(
	name = "thread",
	srcs = glob(["*.java"]),
	deps = ["//src/java/com/dentist/other/standard"]
)